services:
  app:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    restart: on-failure
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
    ports:
      - $PORT:$PORT
    links:
      - db
    command: [sh, -c, "cd /app && npm run start:dev"]

  db:
    build: tools/db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    networks:
      - backend
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT

  adminer:
    build: tools/db/adminer
    networks:
      - backend
    restart: always
    ports:
      - $DB_ADMINER_PORT:$DB_ADMINER_PORT

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
