services:
  db:
    build: ./db
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - ../database:/var/lib/postgresql/data
  adminer:
    build: ./db/adminer
    restart: always
    ports:
      - 8080:8080
